// Generated by scripts/teaching/export-learner-ui-session.ps1.
// Do not edit by hand; update the source scripts or fixtures, then regenerate.
window.openEducationSessionOutput = 
{
  "schemaVersion": 1,
  "sessionAt": "2026-05-25T12:00:00Z",
  "learnerId": "gdev-101-live-smoke-learner",
  "action": {
    "learnerId": "gdev-101-live-smoke-learner",
    "actionType": "lesson",
    "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
    "reason": "no-mastery-evidence",
    "nextReviewAt": null,
    "evidence": "none"
  },
  "prompt": "Write an essay that argues how mechanics, dynamics, and aesthetics work together in a game you know. Use evidence from a specific play experience, compare at least two design alternatives, explain the tradeoffs, and transfer the lesson to a new prototype idea.",
  "hintOptions": [
    {
      "level": "nudge",
      "text": "Start by naming the mechanic, the player behavior it creates, and the feeling or aesthetic result."
    },
    {
      "level": "concept-reminder",
      "text": "Synthesis means connecting ideas, not listing definitions."
    },
    {
      "level": "worked-example",
      "text": "For example, limited inventory can create tension because each pickup choice has opportunity cost; a larger inventory changes the dynamic and weakens that pressure."
    }
  ],
  "learnerProfile": {
    "learnerId": "gdev-101-live-smoke-learner",
    "goals": [
      "game-development:objectives/course/gdev-101/design-vocabulary"
    ],
    "constraints": [
      "short-evening-sessions"
    ],
    "preferences": {
      "explanationStyle": "worked-example",
      "practiceMode": "scaffolded"
    },
    "accommodations": [
      "low-distraction-output"
    ],
    "priorExperience": [
      "played-games-but-new-to-design"
    ]
  },
  "mastery": [
    {
      "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
      "confidence": 0.0,
      "lastEvidenceAt": null,
      "evidenceCount": 0,
      "evidenceSources": []
    }
  ],
  "reviewQueue": [],
  "responseAccepted": true,
  "assessmentItemId": "gdev-synthesis-essay-001",
  "feedback": "This does not yet demonstrate synthesis. Move beyond definitions by connecting concepts, citing evidence, and defending a design judgment.",
  "sourceProvenance": {
    "sourceId": "game-development",
    "sourceRepo": "open-education-game-development",
    "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
    "title": "GDEV-101 Game Design Foundations",
    "license": "CC-BY-4.0 for repo-authored metadata; linked third-party resources retain original licenses",
    "attribution": "Open Education Game Development"
  },
  "updatedStatePath": "F:\\dev\\open-education-suite\\.codex-cache\\tmp\\learner-state.last-session.json"
}
;
window.openEducationLecturePackage = 
{
  "schemaVersion": 1,
  "packageId": "lecture-video:gdev-101-design-vocabulary-short",
  "title": "Design Vocabulary: Verbs, Goals, and Feedback",
  "subjectOwnedAssetRoot": "generated-lectures\\gdev-101-design-vocabulary",
  "contentSource": {
    "sourceId": "game-development",
    "sourceRepo": "open-education-game-development",
    "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
    "title": "GDEV-101 Game Design Foundations"
  },
  "objectiveIds": [
    "game-development:objectives/course/gdev-101/design-vocabulary"
  ],
  "durationSeconds": 180,
  "lessonMode": "short-lecture",
  "deliveryPlan": {
    "audienceMode": "shareable-baseline-with-single-learner-adaptation",
    "baselineUse": "The reusable lecture package covers the objective for a generic learner and can be shared without learner-specific claims.",
    "adaptiveUse": "At session time, the teacher selects pacing, examples, checkpoints, remediation, and the next lecture plan from the single learner's current evidence while still covering the required objective.",
    "sequence": [
      "intro-lecture",
      "diagnostic-check",
      "materials-and-curriculum",
      "guided-practice",
      "progress-assessment",
      "next-lecture-plan"
    ],
    "fullLectureDuration": {
      "targetSeconds": 3000,
      "minimumSeconds": 2700,
      "maximumSeconds": 3300,
      "rationale": "Use about 50 minutes for full class-replacement lectures, but divide the time into short active segments with retrieval, examples, board work, and practice so the learner is not passively watching."
    },
    "segmentCadence": {
      "minimumSegmentSeconds": 300,
      "maximumSegmentSeconds": 720,
      "checkpointEverySeconds": 480,
      "practiceEverySeconds": 900
    },
    "learningEnvironmentPrompts": [
      "Set up a quiet, low-distraction place before starting.",
      "Keep a paper notebook and pen available for vocabulary, sketches, and questions.",
      "Pause at retrieval prompts before the answer is revealed.",
      "Rewrite notes after the lecture into cleaner terms, examples, and remaining questions.",
      "Use the follow-up practice task to produce evidence, not just a feeling of familiarity."
    ],
    "adaptationRequirements": [
      "Always cover every required objective claim and citation in the baseline lecture.",
      "Adapt examples, pacing, remediation, and practice prompts to one learner's evidence.",
      "Do not treat watch time or completion as mastery.",
      "Use diagnostic checks and assessment evidence to plan the next lecture."
    ],
    "boardPlan": {
      "defaultView": "generated-instructor-at-chalkboard",
      "closeUpAvailable": true,
      "closeUpLabel": "Board close-up",
      "moments": [
        {
          "timeSecond": 0,
          "label": "Learning setup",
          "summary": "Quiet space, pen and paper, pause before answers, rewrite notes after the lecture."
        },
        {
          "timeSecond": 35,
          "label": "Verb, goal, feedback loop",
          "summary": "Verb is the action, goal is the target state, feedback is the signal that the action mattered."
        },
        {
          "timeSecond": 95,
          "label": "Theme versus interaction",
          "summary": "Theme describes fiction or setting; interaction names the player action, target, and signal."
        },
        {
          "timeSecond": 135,
          "label": "Practice handoff",
          "summary": "Revise one rule and write what changed in the verb, goal, or feedback loop."
        }
      ]
    }
  },
  "performancePlan": {
    "audioProfile": {
      "voiceStyle": "human masculine instructor with warm, focused energy and natural classroom emotion",
      "voiceMatchPolicy": "match-generated-instructor-gender",
      "targetInstructorGender": "male",
      "targetVoiceGender": "masculine",
      "targetVoiceRegister": "lower adult register with deeper resonance",
      "emotionTargets": [
        "calm confidence during definitions",
        "encouraging curiosity during the worked example",
        "deliberate silence after active-recall prompts",
        "supportive handoff into practice"
      ],
      "prosodyDirectives": [
        "vary pace and emphasis instead of monotone narration",
        "slow slightly before definitions and board labels",
        "use a clear rising invitation before pause prompts",
        "avoid exaggerated synthetic enthusiasm"
      ],
      "ttsRequirements": [
        "sentence-level prosody controls",
        "breath and micro-pause support",
        "deterministic seed or saved provider metadata",
        "local archive of final audio"
      ]
    },
    "pausePrompts": [
      {
        "promptId": "identify-vgf-pause",
        "timeSecond": 60,
        "durationSeconds": 10,
        "prompt": "Pause here: in a familiar game, name one verb, one goal, and one feedback signal.",
        "overlayText": "Pause and write: verb, goal, feedback",
        "resumeCue": "Restart when you are ready to compare your answer.",
        "boardState": "verb-goal-feedback-loop"
      }
    ],
    "visualSync": {
      "boardStates": [
        {
          "stateId": "learning-setup",
          "startSecond": 0,
          "endSecond": 35,
          "boardText": [
            "Quiet space",
            "Pen and paper",
            "Pause before answers",
            "Rewrite notes"
          ],
          "instructorAction": "Faces the learner, points to the setup checklist, then turns to the board."
        },
        {
          "stateId": "verb-goal-feedback-loop",
          "startSecond": 35,
          "endSecond": 95,
          "boardText": [
            "Verb = player action",
            "Goal = target state",
            "Feedback = signal"
          ],
          "instructorAction": "Draws the loop and points to each term as it is defined."
        },
        {
          "stateId": "theme-vs-interaction",
          "startSecond": 95,
          "endSecond": 135,
          "boardText": [
            "Theme is not interaction",
            "Name action + target + signal"
          ],
          "instructorAction": "Crosses out vague theme claims and rewrites them as interaction claims."
        },
        {
          "stateId": "practice-handoff",
          "startSecond": 135,
          "endSecond": 180,
          "boardText": [
            "Revise one rule",
            "Write what changed",
            "Bring evidence"
          ],
          "instructorAction": "Steps aside for board close-up and points to the practice checklist."
        }
      ],
      "minimumBoardStateCoverage": "Every storyboard scene must map to a board state or explicit non-board visual.",
      "staticFramePolicy": "A single static image is allowed only as a placeholder and must not pass publish readiness without a visual-sync review."
    }
  },
  "renderStatus": "rendered-fixture",
  "generatedInstructor": {
    "personaId": "oes-default-generated-instructor-v1",
    "gender": "male",
    "disclosure": "This lecture uses an original generated instructor and synthetic voice for an Open Education Suite lesson.",
    "voiceConsent": "synthetic-project-owned",
    "likenessConsent": "synthetic-project-owned",
    "realPersonClone": false,
    "voiceMatchPolicy": "match-generated-instructor-gender",
    "tone": "clear-rigorous-supportive",
    "realismProfile": {
      "presentationStyle": "realistic-synthetic-instructor-at-chalkboard",
      "renderReadiness": "local-comfyui-avatar-keyframe",
      "visualFidelityTargets": [
        "consistent face, body, lighting, and camera angle across the lecture",
        "natural gaze shifts between learner-facing camera and chalkboard",
        "legible hand and pointer placement that does not cover board work",
        "no real-person face, voice, likeness, catchphrases, or branded style"
      ],
      "movementPlan": [
        "open facing the learner, then turn to the board before drawing the vocabulary loop",
        "point to verb, goal, and feedback labels while naming each term",
        "pause in a neutral listening posture during active recall prompts",
        "step aside or trigger board close-up when dense board work appears"
      ],
      "boardInteractionPlan": [
        "write or reveal each chalkboard label when the narration reaches it",
        "keep the instructor body outside the high-priority board text area",
        "support a board close-up crop for each listed board moment"
      ]
    }
  },
  "sourceReview": [
    {
      "sourceType": "course-source",
      "title": "GDEV-101 Game Design Foundations",
      "sourceId": "game-development",
      "sourceRepo": "open-education-game-development",
      "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
      "usedFor": "grounding",
      "copyingAllowed": false,
      "notes": "Grounds the lesson in design vocabulary, verbs, goals, feedback, active prototyping, and playtest evidence."
    },
    {
      "sourceType": "teaching-pattern",
      "title": "Short studio lecture pattern",
      "usedFor": "structure-only",
      "copyingAllowed": false,
      "notes": "Uses a brief opening problem, worked example, active recall pause, misconception check, and practice handoff."
    }
  ],
  "citations": [
    {
      "citationId": "course-gdev-101",
      "sourceId": "game-development",
      "sourceRepo": "open-education-game-development",
      "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
      "claim": "The course covers design vocabulary, verbs, goals, feedback, playtesting, and prototypes."
    }
  ],
  "script": {
    "format": "markdown",
    "text": "# Design Vocabulary: Verbs, Goals, and Feedback\n\nBefore we start, set up the way a strong in-person class expects you to learn: quiet space, pen and paper open, and a plan to pause before answering. Do not only watch. Listen, write the important words by hand, and after the lecture rewrite the notes in cleaner language with one example of your own.\n\nToday we will use three design words precisely: verb, goal, and feedback. A verb is what the player can do. A goal is what the player is trying to accomplish. Feedback is how the game tells the player what changed and whether the action mattered. In GDEV-101, this vocabulary supports prototype critique and playtest evidence rather than personal preference alone. [course-gdev-101]\n\nOn the board, draw a loop with three labels: verb, goal, feedback. Consider a simple rule-change prototype. If the player can only move, but there is no goal, the activity may be a toy instead of a game. If the goal exists but feedback is weak, the player cannot judge progress. Pause here: in a familiar game, name one verb, one goal, and one feedback signal before the labels are revealed.\n\nA common mistake is to describe theme instead of interaction. Saying a game is about space does not identify the verb. Saying the player wants to win does not identify the local goal. Strong critique names the action, the target, and the signal.\n\nAfter the video, revise one rule in a familiar game and write what changed in the verb, goal, or feedback loop. Bring that to the next practice checkpoint. The adaptive teacher will use your checkpoint and assessment evidence to plan what the next lecture should emphasize. [course-gdev-101]"
  },
  "storyboard": [
    {
      "sceneId": "open-problem",
      "startSecond": 0,
      "endSecond": 35,
      "visual": "Generated instructor at a chalkboard labeled quiet setup, pen and paper, pause, rewrite notes.",
      "narrationCue": "Prepare the learning environment and introduce the three vocabulary terms.",
      "activeRecallPrompt": null,
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "worked-example",
      "startSecond": 35,
      "endSecond": 95,
      "visual": "Chalkboard close-up shows a loop: verb points to goal, goal points to feedback, feedback points back to next action.",
      "narrationCue": "Work through one prototype example using verb, goal, and feedback.",
      "activeRecallPrompt": "Name the verb, goal, and feedback signal before the labels appear.",
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "misconception-check",
      "startSecond": 95,
      "endSecond": 135,
      "visual": "Chalkboard close-up contrasts theme words with interaction words.",
      "narrationCue": "Separate theme from interaction and warn against vague critique.",
      "activeRecallPrompt": "Is 'space adventure' a verb, goal, feedback signal, or theme?",
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "practice-handoff",
      "startSecond": 135,
      "endSecond": 180,
      "visual": "Generated instructor highlights a chalkboard checklist for a rule-change prototype reflection.",
      "narrationCue": "Send the learner into the first GDEV-101 practice task.",
      "activeRecallPrompt": "Choose one familiar game and plan one rule change.",
      "citationIds": [
        "course-gdev-101"
      ]
    }
  ],
  "transcript": {
    "format": "plain-text",
    "language": "en",
    "text": "Before we start, set up a quiet learning space, keep a paper notebook and pen available, and plan to pause before answering. Listen, write the important words by hand, and after the lecture rewrite the notes in cleaner language with one example of your own. Today we will use three design words precisely: verb, goal, and feedback. A verb is what the player can do. A goal is what the player is trying to accomplish. Feedback is how the game tells the player what changed and whether the action mattered. Consider a simple rule-change prototype. If the player can only move, but there is no goal, the activity may be a toy instead of a game. If the goal exists but feedback is weak, the player cannot judge progress. Pause here: in a familiar game, name one verb, one goal, and one feedback signal. A common mistake is to describe theme instead of interaction. Saying a game is about space does not identify the verb. Saying the player wants to win does not identify the local goal. Strong critique names the action, the target, and the signal. After the video, revise one rule in a familiar game and write what changed in the verb, goal, or feedback loop. The adaptive teacher will use your checkpoint and assessment evidence to plan what the next lecture should emphasize."
  },
  "captions": {
    "format": "webvtt",
    "language": "en",
    "text": "WEBVTT\n\n00:00:00.000 --> 00:00:35.000\nSet up a quiet learning space with pen and paper, then use three design words precisely: verb, goal, and feedback.\n\n00:00:35.000 --> 00:01:35.000\nConsider a simple rule-change prototype. Pause here: in a familiar game, name one verb, one goal, and one feedback signal.\n\n00:01:35.000 --> 00:02:15.000\nA common mistake is to describe theme instead of interaction.\n\n00:02:15.000 --> 00:03:00.000\nAfter the video, revise one rule, rewrite your notes, and bring evidence to the next checkpoint."
  },
  "chapters": [
    {
      "title": "Vocabulary",
      "startSecond": 0
    },
    {
      "title": "Worked Example",
      "startSecond": 35
    },
    {
      "title": "Misconception Check",
      "startSecond": 95
    },
    {
      "title": "Practice Handoff",
      "startSecond": 135
    }
  ],
  "slides": [
    {
      "slideId": "slide-001",
      "title": "Verb, Goal, Feedback",
      "path": "slides\\001-verb-goal-feedback.md",
      "altText": "A chalkboard loop with three labels around a prototype: player verb, target goal, and feedback signal.",
      "attribution": "Original generated slide from the cited GDEV-101 course source."
    },
    {
      "slideId": "slide-002",
      "title": "Theme Is Not Interaction",
      "path": "slides\\002-theme-vs-interaction.md",
      "altText": "A chalkboard comparison table separating vague theme words from concrete player actions and signals.",
      "attribution": "Original generated slide from the cited GDEV-101 course source."
    }
  ],
  "media": [
    {
      "assetId": "lecture-video-mp4",
      "type": "video/mp4",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\video\\lecture-video-mp4.mp4",
      "sha256": "48c05403cdfdc943bb95c74690dd633123afb3f03bdd6a63acc0e666d70f6c42",
      "status": "archived",
      "requiredForPublish": true,
      "length": 3186432
    },
    {
      "assetId": "lecture-audio-m4a",
      "type": "audio/mp4",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\audio\\lecture-audio-m4a.m4a",
      "sha256": "9578edf9d9f1f9ec7aa615398961bc7af4f9ec4099f0a27de7e4891c4252162f",
      "status": "archived",
      "requiredForPublish": true,
      "length": 1310308
    },
    {
      "assetId": "lecture-audio-neural-tts",
      "type": "audio/mpeg",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\audio\\lecture-audio-neural-tts.mp3",
      "sha256": "062ef64674137f8747698a78a3732c510d53a8ee2b7fc1e61706da562283c025",
      "status": "archived",
      "requiredForPublish": false
    },
    {
      "assetId": "lecture-avatar-comfyui-png",
      "type": "image/png",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\visuals\\lecture-avatar-comfyui.png",
      "sha256": "0585cf05f33bad66ec2125d12f78c76f50ad5b296b6eb86662d02993c8e92e43",
      "status": "archived",
      "requiredForPublish": false
    },
    {
      "assetId": "lecture-audio-wav-fixture",
      "type": "audio/wav",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\audio\\lecture-audio-wav.wav",
      "sha256": "8dfe7e84eb9886ead840872ccb7f1f85af91eea3a55b658e983b8bab3174a840",
      "status": "archived",
      "requiredForPublish": false
    },
    {
      "assetId": "lecture-guided-camera-mp4",
      "type": "video/mp4",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\video\\lecture-guided-camera-mp4.mp4",
      "sha256": "30dee51bf6ca9eddecead21b1a2d27149d8592c810f0e978337fad8f38f7dcf5",
      "length": 2949541,
      "status": "archived",
      "requiredForPublish": false,
      "visualSyncMode": "board-close-up-guided-camera",
      "sourceAssetIds": [
        "lecture-video-mp4",
        "lecture-board-close-up-mp4"
      ],
      "cameraPlanSource": "visualSync.cameraPlan",
      "audioPreserved": true,
      "transcriptPreserved": true,
      "checkpointContextPreserved": true,
      "classroomContextPreserved": true
    },
    {
      "assetId": "lecture-board-close-up-mp4",
      "type": "video/mp4",
      "path": "generated-lectures\\gdev-101-design-vocabulary\\media\\video\\lecture-board-close-up-mp4.mp4",
      "sha256": "3774d8445acae4d9bed9a4d194727be99515e43cb4dc809843846041eec37935",
      "length": 2262376,
      "status": "archived",
      "requiredForPublish": false,
      "visualSyncMode": "board-close-up-crop",
      "sourceAssetId": "lecture-video-mp4",
      "cropSource": "visualSync.boardSurface.closeUpCrop",
      "audioPreserved": true,
      "transcriptPreserved": true,
      "checkpointContextPreserved": true,
      "classroomContextPreserved": true
    }
  ],
  "licenseAudit": {
    "status": "pass",
    "externalHostDependency": false,
    "requiredInstructionArchive": "generated-lectures\\gdev-101-design-vocabulary\\publish\\lecture-video.publish-ready.json",
    "blockedMaterials": [],
    "notes": [
      "No copied third-party transcript, slides, voice, likeness, or hosted video is used.",
      "The lesson is an original generated artifact grounded in the cited course source."
    ]
  },
  "qaStatus": {
    "status": "pass",
    "checks": [
      {
        "checkId": "source-grounding",
        "status": "pass",
        "evidence": "Script and storyboard cite course-gdev-101."
      },
      {
        "checkId": "license-safety",
        "status": "pass",
        "evidence": "Generated instructor is synthetic and no external hosted media is required."
      },
      {
        "checkId": "accessibility",
        "status": "pass",
        "evidence": "Captions, transcript, chapters, and slide alt text are present."
      },
      {
        "checkId": "active-recall",
        "status": "pass",
        "evidence": "Storyboard includes recall prompts before answers are revealed."
      },
      {
        "checkId": "assessment-handoff",
        "status": "pass",
        "evidence": "Practice handoff asks for a rule-change prototype reflection."
      }
    ]
  },
  "operatorReview": {
    "workflowId": "lecture-operator-review-v1",
    "publishStatus": "approved-for-publish",
    "stages": [
      {
        "stageId": "script",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:00:00Z",
        "evidence": [
          "Course citation markers are present.",
          "Narration is original and includes a misconception check."
        ],
        "notes": "Approved as a deterministic scripted fixture."
      },
      {
        "stageId": "visuals",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:01:00Z",
        "evidence": [
          "Slide plan uses original generated visuals.",
          "Slides include meaningful alt text and attribution."
        ],
        "notes": "Approved for storyboard and slide metadata."
      },
      {
        "stageId": "media",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-26T12:00:00Z",
        "evidence": [
          "Required media archived under generated-lectures\\gdev-101-design-vocabulary.",
          "SHA-256 checksums recorded for lecture-video-mp4 and lecture-audio-m4a.",
          "Board-local pause prompt timing reviewed in the rendered media."
        ],
        "notes": "Approved for deterministic rendered publish fixture."
      },
      {
        "stageId": "accessibility",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:02:00Z",
        "evidence": [
          "Transcript, WebVTT captions, chapters, and slide alt text are present."
        ],
        "notes": "Approved for the text and metadata fixture."
      },
      {
        "stageId": "license-persona",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:03:00Z",
        "evidence": [
          "License audit passes.",
          "Generated instructor persona and disclosure match the approved policy."
        ],
        "notes": "Approved for synthetic instructor and source boundaries."
      },
      {
        "stageId": "instructor-realism",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-26T12:00:00Z",
        "evidence": [
          "Face/body consistency reviewed against the local ComfyUI avatar keyframe and realismProfile.",
          "Front-row framing reviewed so the learner has an easy view of the instructor and chalkboard.",
          "Board readability reviewed for the board-local writing layer and chalkboard contrast.",
          "Board occlusion reviewed so the instructor does not cover high-priority board text and board close-up remains available.",
          "Board close-up usefulness reviewed against the recorded board surface crop.",
          "Gesture timing reviewed against storyboard board moments, narration cues, and active-recall pauses.",
          "Lip-sync timing reviewed against final instructor audio and active-recall pause silence.",
          "Gaze direction reviewed for learner-facing explanation, board-facing writing, and return-to-learner cues.",
          "Head and hand motion naturalness reviewed for subtle classroom movement without distracting jitter.",
          "Board-writing gesture synchronization reviewed so pointing and writing gestures align to board-local chalk marks.",
          "No whole-frame teaching text overlays are used; instructional writing is constrained to the board surface.",
          "Generated instructor disclosure reviewed before publish: This lecture uses an original generated instructor and synthetic voice for an Open Education Suite lesson."
        ],
        "notes": "Approved for local ComfyUI avatar keyframe realism review."
      },
      {
        "stageId": "final-package",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-26T12:00:00Z",
        "evidence": [
          "All required review stages are approved.",
          "Publish-ready path recorded: generated-lectures\\gdev-101-design-vocabulary\\publish\\lecture-video.publish-ready.json"
        ],
        "notes": "Approved for deterministic publish gate fixture."
      }
    ],
    "finalApproval": {
      "status": "approved",
      "reviewer": "operator-fixture",
      "reviewedAt": "2026-05-26T12:05:00Z",
      "notes": "Final package approval recorded for generated-lectures\\gdev-101-design-vocabulary\\publish\\lecture-video.publish-ready.json."
    }
  },
  "adaptiveHooks": {
    "availableModes": [
      "video",
      "transcript",
      "audio"
    ],
    "checkpointPolicy": "checkpoint-evidence-only",
    "checkpoints": [
      {
        "checkpointId": "identify-vgf",
        "timeSecond": 60,
        "prompt": "In a familiar game, identify one verb, one goal, and one feedback signal.",
        "evidenceType": "short-answer",
        "masteryImpact": "proposal-only"
      },
      {
        "checkpointId": "theme-vs-interaction",
        "timeSecond": 110,
        "prompt": "Is 'space adventure' a verb, goal, feedback signal, or theme?",
        "evidenceType": "multiple-choice",
        "masteryImpact": "proposal-only"
      }
    ],
    "followUpAction": {
      "type": "practice",
      "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
      "prompt": "Revise one rule in a familiar game and explain what changed in the verb, goal, or feedback loop."
    }
  },
  "contentRepoRoot": "F:\\dev\\open-education-game-development",
  "contentRepoWebRoot": "file:///F:/dev/open-education-game-development/",
  "contentRepoHttpRoot": "/content-repos/open-education-game-development/",
  "sourcePackagePath": "generated-lectures\\gdev-101-design-vocabulary\\publish\\lecture-video.publish-ready.json"
}
;
window.openEducationContentCatalog = 
{
  "schemaVersion": 1,
  "generatedFrom": "scripts/ingestion/scan-content-sources.ps1",
  "sourceCount": 10,
  "sources": [
    {
      "sourceId": "cybersecurity",
      "title": "Open Education Cybersecurity",
      "sourceRepo": "open-education-cybersecurity",
      "objectCount": 12,
      "courses": [
        {
          "id": "cybersecurity:study-plans/courses/CYB-101-cybersecurity-defense-foundations.md",
          "title": "CYB-101 Cybersecurity Defense Foundations",
          "sourceRepo": "open-education-cybersecurity",
          "sourcePath": "study-plans\\courses\\CYB-101-cybersecurity-defense-foundations.md",
          "objectives": [
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/security-thinking",
              "label": "Security Thinking"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/network-and-identity-basics",
              "label": "Network And Identity Basics"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/threat-modeling",
              "label": "Threat Modeling"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/control-selection",
              "label": "Control Selection"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/application-risk",
              "label": "Application Risk"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/log-triage",
              "label": "Log Triage"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/incident-response",
              "label": "Incident Response"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/risk-communication",
              "label": "Risk Communication"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/ethics-and-authorization",
              "label": "Ethics And Authorization"
            },
            {
              "objectiveId": "cybersecurity:objectives/course/cyb-101/capstone-defense",
              "label": "Capstone Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/application-risk",
          "label": "Application Risk"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/capstone-defense",
          "label": "Capstone Defense"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/control-selection",
          "label": "Control Selection"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/ethics-and-authorization",
          "label": "Ethics And Authorization"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/incident-response",
          "label": "Incident Response"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/log-triage",
          "label": "Log Triage"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/network-and-identity-basics",
          "label": "Network And Identity Basics"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/risk-communication",
          "label": "Risk Communication"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/security-thinking",
          "label": "Security Thinking"
        },
        {
          "objectiveId": "cybersecurity:objectives/course/cyb-101/threat-modeling",
          "label": "Threat Modeling"
        },
        {
          "objectiveId": "cybersecurity:objectives/incident-triage",
          "label": "Incident Triage"
        },
        {
          "objectiveId": "cybersecurity:objectives/network-fundamentals",
          "label": "Network Fundamentals"
        },
        {
          "objectiveId": "cybersecurity:objectives/threat-modeling-basics",
          "label": "Threat Modeling Basics"
        }
      ]
    },
    {
      "sourceId": "clear-reasoning",
      "title": "Open Education Clear Reasoning",
      "sourceRepo": "open-education-clear-reasoning",
      "objectCount": 8,
      "courses": [
        {
          "id": "clear-reasoning:study-plans/courses/CR-101-clear-reasoning-foundations.md",
          "title": "CR-101 Clear Reasoning Foundations",
          "sourceRepo": "open-education-clear-reasoning",
          "sourcePath": "study-plans\\courses\\CR-101-clear-reasoning-foundations.md",
          "objectives": [
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/attention-and-distinction",
              "label": "Attention And Distinction"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/definitions-and-categories",
              "label": "Definitions And Categories"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/propositions-and-contradiction",
              "label": "Propositions And Contradiction"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/proof-craft",
              "label": "Proof Craft"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/inference-and-validity",
              "label": "Inference And Validity"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/dialectical-questions",
              "label": "Dialectical Questions"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/fallacy-repair",
              "label": "Fallacy Repair"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/ethical-rhetoric",
              "label": "Ethical Rhetoric"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/disagreement-discipline",
              "label": "Disagreement Discipline"
            },
            {
              "objectiveId": "clear-reasoning:objectives/course/cr-101/capstone-defense",
              "label": "Capstone Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/attention-and-distinction",
          "label": "Attention And Distinction"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/capstone-defense",
          "label": "Capstone Defense"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/definitions-and-categories",
          "label": "Definitions And Categories"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/dialectical-questions",
          "label": "Dialectical Questions"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/disagreement-discipline",
          "label": "Disagreement Discipline"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/ethical-rhetoric",
          "label": "Ethical Rhetoric"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/fallacy-repair",
          "label": "Fallacy Repair"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/inference-and-validity",
          "label": "Inference And Validity"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/proof-craft",
          "label": "Proof Craft"
        },
        {
          "objectiveId": "clear-reasoning:objectives/course/cr-101/propositions-and-contradiction",
          "label": "Propositions And Contradiction"
        }
      ]
    },
    {
      "sourceId": "data-science",
      "title": "Open Education Data Science",
      "sourceRepo": "open-education-data-science",
      "objectCount": 12,
      "courses": [
        {
          "id": "data-science:study-plans/courses/DS-101-data-science-evidence-and-modeling.md",
          "title": "DS-101 Data Science Evidence And Modeling",
          "sourceRepo": "open-education-data-science",
          "sourcePath": "study-plans\\courses\\DS-101-data-science-evidence-and-modeling.md",
          "objectives": [
            {
              "objectiveId": "data-science:objectives/course/ds-101/question-and-evidence",
              "label": "Question And Evidence"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/data-audit",
              "label": "Data Audit"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/summary-statistics",
              "label": "Summary Statistics"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/visual-reasoning",
              "label": "Visual Reasoning"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/baseline-modeling",
              "label": "Baseline Modeling"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/evaluation-and-overfitting",
              "label": "Evaluation And Overfitting"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/causal-caution",
              "label": "Causal Caution"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/reproducible-workflow",
              "label": "Reproducible Workflow"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/communication",
              "label": "Communication"
            },
            {
              "objectiveId": "data-science:objectives/course/ds-101/capstone-defense",
              "label": "Capstone Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "data-science:objectives/course/ds-101/baseline-modeling",
          "label": "Baseline Modeling"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/capstone-defense",
          "label": "Capstone Defense"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/causal-caution",
          "label": "Causal Caution"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/communication",
          "label": "Communication"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/data-audit",
          "label": "Data Audit"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/evaluation-and-overfitting",
          "label": "Evaluation And Overfitting"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/question-and-evidence",
          "label": "Question And Evidence"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/reproducible-workflow",
          "label": "Reproducible Workflow"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/summary-statistics",
          "label": "Summary Statistics"
        },
        {
          "objectiveId": "data-science:objectives/course/ds-101/visual-reasoning",
          "label": "Visual Reasoning"
        },
        {
          "objectiveId": "data-science:objectives/data-cleaning-basics",
          "label": "Data Cleaning Basics"
        },
        {
          "objectiveId": "data-science:objectives/regression-basics",
          "label": "Regression Basics"
        },
        {
          "objectiveId": "data-science:objectives/visualization-basics",
          "label": "Visualization Basics"
        }
      ]
    },
    {
      "sourceId": "game-development",
      "title": "Open Education Game Development",
      "sourceRepo": "open-education-game-development",
      "objectCount": 44,
      "courses": [
        {
          "id": "game-development:study-plans/courses/GDEV-010-onboarding-studio.md",
          "title": "GDEV-010 Onboarding Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-010-onboarding-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-010/toolchain-readiness",
              "label": "Toolchain Readiness"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-010/build-discipline",
              "label": "Build Discipline"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-101-game-design-foundations.md",
          "title": "GDEV-101 Game Design Foundations",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
              "label": "Design Vocabulary"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-101/prototype-iteration",
              "label": "Prototype Iteration"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-102-programming-for-games.md",
          "title": "GDEV-102 Programming for Games",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-102-programming-for-games.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-102/programming-fundamentals",
              "label": "Programming Fundamentals"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-102/code-architecture-basics",
              "label": "Code Architecture Basics"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-103-game-math-physics.md",
          "title": "GDEV-103 Game Math and Physics",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-103-game-math-physics.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-103/game-math",
              "label": "Game Math"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-103/game-physics",
              "label": "Game Physics"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-104-engine-tools-workflows.md",
          "title": "GDEV-104 Engine Tools and Workflows",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-104-engine-tools-workflows.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-104/engine-literacy",
              "label": "Engine Literacy"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-104/source-control-workflow",
              "label": "Source Control Workflow"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-201-gameplay-systems-architecture.md",
          "title": "GDEV-201 Gameplay Systems Architecture",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-201-gameplay-systems-architecture.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-201/gameplay-systems",
              "label": "Gameplay Systems"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-201/technical-writing",
              "label": "Technical Writing"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-202-level-design-ux-narrative.md",
          "title": "GDEV-202 Level Design, UX, and Narrative",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-202-level-design-ux-narrative.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-202/level-flow",
              "label": "Level Flow"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-202/ux-research",
              "label": "Ux Research"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-203-art-animation-audio-ui-pipeline.md",
          "title": "GDEV-203 Art, Animation, Audio, and UI Pipeline",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-203-art-animation-audio-ui-pipeline.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-203/content-pipeline",
              "label": "Content Pipeline"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-203/feedback-polish",
              "label": "Feedback Polish"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-204-ai-simulation-procedural-systems.md",
          "title": "GDEV-204 AI, Simulation, and Procedural Systems",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-204-ai-simulation-procedural-systems.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-204/game-ai",
              "label": "Game Ai"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-204/procedural-systems",
              "label": "Procedural Systems"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-301-production-qa-analytics-live-ops.md",
          "title": "GDEV-301 Production, QA, Analytics, and Live Operations",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-301-production-qa-analytics-live-ops.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-301/production-planning",
              "label": "Production Planning"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-301/qa-analytics-liveops",
              "label": "Qa Analytics Liveops"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-302-multiplayer-online-systems.md",
          "title": "GDEV-302 Multiplayer and Online Systems",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-302-multiplayer-online-systems.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-302/networking-literacy",
              "label": "Networking Literacy"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-302/networked-prototype",
              "label": "Networked Prototype"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-303-performance-platforms-accessibility-compliance.md",
          "title": "GDEV-303 Performance, Platforms, Accessibility, and Compliance",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-303-performance-platforms-accessibility-compliance.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-303/performance-profiling",
              "label": "Performance Profiling"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-303/accessibility-compliance",
              "label": "Accessibility Compliance"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-401-specialization-studio.md",
          "title": "GDEV-401 Specialization Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-401-specialization-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-401/specialization-depth",
              "label": "Specialization Depth"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-401/external-critique",
              "label": "External Critique"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-402-team-style-vertical-slice-studio.md",
          "title": "GDEV-402 Team-Style Vertical Slice Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-402-team-style-vertical-slice-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-402/vertical-slice-production",
              "label": "Vertical Slice Production"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-402/interdisciplinary-handoff",
              "label": "Interdisciplinary Handoff"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-499-capstone-launch.md",
          "title": "GDEV-499 Capstone Launch",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-499-capstone-launch.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-499/capstone-launch",
              "label": "Capstone Launch"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-499/portfolio-case-study",
              "label": "Portfolio Case Study"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "game-development:objectives/accessibility-aware-design",
          "label": "Accessibility Aware Design"
        },
        {
          "objectiveId": "game-development:objectives/art-pipeline-literacy",
          "label": "Art Pipeline Literacy"
        },
        {
          "objectiveId": "game-development:objectives/audio-feedback-literacy",
          "label": "Audio Feedback Literacy"
        },
        {
          "objectiveId": "game-development:objectives/blueprint-to-cpp",
          "label": "Blueprint To Cpp"
        },
        {
          "objectiveId": "game-development:objectives/capstone-launch",
          "label": "Capstone Launch"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-010/build-discipline",
          "label": "Build Discipline"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-010/toolchain-readiness",
          "label": "Toolchain Readiness"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
          "label": "Design Vocabulary"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-101/prototype-iteration",
          "label": "Prototype Iteration"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-102/code-architecture-basics",
          "label": "Code Architecture Basics"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-102/programming-fundamentals",
          "label": "Programming Fundamentals"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-103/game-math",
          "label": "Game Math"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-103/game-physics",
          "label": "Game Physics"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-104/engine-literacy",
          "label": "Engine Literacy"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-104/source-control-workflow",
          "label": "Source Control Workflow"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-201/gameplay-systems",
          "label": "Gameplay Systems"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-201/technical-writing",
          "label": "Technical Writing"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-202/level-flow",
          "label": "Level Flow"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-202/ux-research",
          "label": "Ux Research"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-203/content-pipeline",
          "label": "Content Pipeline"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-203/feedback-polish",
          "label": "Feedback Polish"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-204/game-ai",
          "label": "Game Ai"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-204/procedural-systems",
          "label": "Procedural Systems"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-301/production-planning",
          "label": "Production Planning"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-301/qa-analytics-liveops",
          "label": "Qa Analytics Liveops"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-302/networked-prototype",
          "label": "Networked Prototype"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-302/networking-literacy",
          "label": "Networking Literacy"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-303/accessibility-compliance",
          "label": "Accessibility Compliance"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-303/performance-profiling",
          "label": "Performance Profiling"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-401/external-critique",
          "label": "External Critique"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-401/specialization-depth",
          "label": "Specialization Depth"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-402/interdisciplinary-handoff",
          "label": "Interdisciplinary Handoff"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-402/vertical-slice-production",
          "label": "Vertical Slice Production"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-499/capstone-launch",
          "label": "Capstone Launch"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-499/portfolio-case-study",
          "label": "Portfolio Case Study"
        },
        {
          "objectiveId": "game-development:objectives/design-core-loop",
          "label": "Design Core Loop"
        },
        {
          "objectiveId": "game-development:objectives/game-ai-simulation",
          "label": "Game Ai Simulation"
        },
        {
          "objectiveId": "game-development:objectives/game-math-and-physics",
          "label": "Game Math And Physics"
        },
        {
          "objectiveId": "game-development:objectives/gameplay-architecture",
          "label": "Gameplay Architecture"
        },
        {
          "objectiveId": "game-development:objectives/level-flow",
          "label": "Level Flow"
        },
        {
          "objectiveId": "game-development:objectives/performance-profiling",
          "label": "Performance Profiling"
        },
        {
          "objectiveId": "game-development:objectives/playtest-driven-iteration",
          "label": "Playtest Driven Iteration"
        },
        {
          "objectiveId": "game-development:objectives/portfolio-case-study",
          "label": "Portfolio Case Study"
        },
        {
          "objectiveId": "game-development:objectives/qa-release-readiness",
          "label": "Qa Release Readiness"
        },
        {
          "objectiveId": "game-development:objectives/scope-control",
          "label": "Scope Control"
        },
        {
          "objectiveId": "game-development:objectives/team-style-handoff",
          "label": "Team Style Handoff"
        },
        {
          "objectiveId": "game-development:objectives/tools-and-pipeline",
          "label": "Tools And Pipeline"
        },
        {
          "objectiveId": "game-development:objectives/ui-ux-game-feedback",
          "label": "Ui Ux Game Feedback"
        },
        {
          "objectiveId": "game-development:objectives/unreal-basics",
          "label": "Unreal Basics"
        },
        {
          "objectiveId": "game-development:objectives/vertical-slice-production",
          "label": "Vertical Slice Production"
        },
        {
          "objectiveId": "game-development:objectives/vr-comfort-basics",
          "label": "Vr Comfort Basics"
        }
      ]
    },
    {
      "sourceId": "mens-relationship-skills",
      "title": "Open Education Men's Relationship Skills",
      "sourceRepo": "open-education-mens-relationship-skills",
      "objectCount": 19,
      "courses": [
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-010-onboarding-ethics-and-personal-code.md",
          "title": "MRS-010 - Onboarding, Ethics, And Personal Code",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-010-onboarding-ethics-and-personal-code.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-010/personal-code",
              "label": "Personal Code"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-010/ethical-guardrails",
              "label": "Ethical Guardrails"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-101-inner-strength-and-grounded-confidence.md",
          "title": "MRS-101 - Inner Strength And Grounded Confidence",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-101-inner-strength-and-grounded-confidence.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/emotional-regulation",
              "label": "Emotional Regulation"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/competence-confidence",
              "label": "Competence Confidence"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/fellowship-and-elevation",
              "label": "Fellowship And Elevation"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-102-communication-and-social-intelligence.md",
          "title": "MRS-102 - Communication And Social Intelligence",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-102-communication-and-social-intelligence.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-102/active-listening",
              "label": "Active Listening"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-102/conversational-reciprocity",
              "label": "Conversational Reciprocity"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-201-ethical-attraction-and-dating-practice.md",
          "title": "MRS-201 - Ethical Attraction And Dating Practice",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-201-ethical-attraction-and-dating-practice.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-201/ethical-attraction",
              "label": "Ethical Attraction"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-201/initiative-and-boundaries",
              "label": "Initiative And Boundaries"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-301-relationship-discernment-and-commitment.md",
          "title": "MRS-301 - Relationship Discernment And Commitment",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-301-relationship-discernment-and-commitment.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/partner-discernment",
              "label": "Partner Discernment"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/presentation-vs-character-discernment",
              "label": "Presentation Vs Character Discernment"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/healthy-commitment",
              "label": "Healthy Commitment"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/family-template-discernment",
              "label": "Family Template Discernment"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/values-aligned-partner-search",
              "label": "Values Aligned Partner Search"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-302-trust-fidelity-and-relationship-reality-checks.md",
          "title": "MRS-302 - Trust, Fidelity, And Relationship Reality Checks",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-302-trust-fidelity-and-relationship-reality-checks.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-302/trust-pattern-discernment",
              "label": "Trust Pattern Discernment"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-302/fidelity-response-plan",
              "label": "Fidelity Response Plan"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-303-modern-dating-safety-sexual-health-and-practical-partnership.md",
          "title": "MRS-303 - Modern Dating Safety, Sexual Health, And Practical Partnership",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-303-modern-dating-safety-sexual-health-and-practical-partnership.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/online-dating-safety",
              "label": "Online Dating Safety"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/sexual-health-family-planning",
              "label": "Sexual Health Family Planning"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/breakup-recovery",
              "label": "Breakup Recovery"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/practical-partnership",
              "label": "Practical Partnership"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/safety-referral-boundaries",
              "label": "Safety Referral Boundaries"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-304-healthy-sexuality-porn-reality-and-mutual-pleasure.md",
          "title": "MRS-304 - Healthy Sexuality, Porn Reality, And Mutual Pleasure",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-304-healthy-sexuality-porn-reality-and-mutual-pleasure.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/porn-reality-and-body-confidence",
              "label": "Porn Reality And Body Confidence"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/sexual-habit-recovery",
              "label": "Sexual Habit Recovery"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/anatomy-function-and-medical-humility",
              "label": "Anatomy Function And Medical Humility"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/consent-and-pleasure-communication",
              "label": "Consent And Pleasure Communication"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/arousal-pacing-and-self-command",
              "label": "Arousal Pacing And Self Command"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/fantasy-boundaries-and-values",
              "label": "Fantasy Boundaries And Values"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/mutual-attention-and-feedback",
              "label": "Mutual Attention And Feedback"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-401-marriage-preparation-and-relationship-practice.md",
          "title": "MRS-401 - Marriage Preparation And Relationship Practice",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-401-marriage-preparation-and-relationship-practice.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/marriage-readiness-self-audit",
              "label": "Marriage Readiness Self Audit"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/opposite-sex-social-practice",
              "label": "Opposite Sex Social Practice"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/courtship-intention-and-pacing",
              "label": "Courtship Intention And Pacing"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/hard-conversation-readiness",
              "label": "Hard Conversation Readiness"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/marriage-conflict-repair",
              "label": "Marriage Conflict Repair"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/shared-life-systems",
              "label": "Shared Life Systems"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/family-and-community-integration",
              "label": "Family And Community Integration"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/commitment-discernment-and-exit",
              "label": "Commitment Discernment And Exit"
            }
          ]
        },
        {
          "id": "mens-relationship-skills:study-plans/courses/MRS-499-capstone-relational-character-portfolio.md",
          "title": "MRS-499 - Capstone Relational Character Portfolio",
          "sourceRepo": "open-education-mens-relationship-skills",
          "sourcePath": "study-plans\\courses\\MRS-499-capstone-relational-character-portfolio.md",
          "objectives": [
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/integrated-scenario-performance",
              "label": "Integrated Scenario Performance"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/portfolio-self-audit",
              "label": "Portfolio Self Audit"
            },
            {
              "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/fellowship-leadership",
              "label": "Fellowship Leadership"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-010/ethical-guardrails",
          "label": "Ethical Guardrails"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-010/personal-code",
          "label": "Personal Code"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/competence-confidence",
          "label": "Competence Confidence"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/emotional-regulation",
          "label": "Emotional Regulation"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-101/fellowship-and-elevation",
          "label": "Fellowship And Elevation"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-102/active-listening",
          "label": "Active Listening"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-102/conversational-reciprocity",
          "label": "Conversational Reciprocity"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-201/ethical-attraction",
          "label": "Ethical Attraction"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-201/initiative-and-boundaries",
          "label": "Initiative And Boundaries"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/family-template-discernment",
          "label": "Family Template Discernment"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/healthy-commitment",
          "label": "Healthy Commitment"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/partner-discernment",
          "label": "Partner Discernment"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/presentation-vs-character-discernment",
          "label": "Presentation Vs Character Discernment"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-301/values-aligned-partner-search",
          "label": "Values Aligned Partner Search"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-302/fidelity-response-plan",
          "label": "Fidelity Response Plan"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-302/trust-pattern-discernment",
          "label": "Trust Pattern Discernment"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/breakup-recovery",
          "label": "Breakup Recovery"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/online-dating-safety",
          "label": "Online Dating Safety"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/practical-partnership",
          "label": "Practical Partnership"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/safety-referral-boundaries",
          "label": "Safety Referral Boundaries"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-303/sexual-health-family-planning",
          "label": "Sexual Health Family Planning"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/anatomy-function-and-medical-humility",
          "label": "Anatomy Function And Medical Humility"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/arousal-pacing-and-self-command",
          "label": "Arousal Pacing And Self Command"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/consent-and-pleasure-communication",
          "label": "Consent And Pleasure Communication"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/fantasy-boundaries-and-values",
          "label": "Fantasy Boundaries And Values"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/mutual-attention-and-feedback",
          "label": "Mutual Attention And Feedback"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/porn-reality-and-body-confidence",
          "label": "Porn Reality And Body Confidence"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-304/sexual-habit-recovery",
          "label": "Sexual Habit Recovery"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/commitment-discernment-and-exit",
          "label": "Commitment Discernment And Exit"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/courtship-intention-and-pacing",
          "label": "Courtship Intention And Pacing"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/family-and-community-integration",
          "label": "Family And Community Integration"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/hard-conversation-readiness",
          "label": "Hard Conversation Readiness"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/marriage-conflict-repair",
          "label": "Marriage Conflict Repair"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/marriage-readiness-self-audit",
          "label": "Marriage Readiness Self Audit"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/opposite-sex-social-practice",
          "label": "Opposite Sex Social Practice"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-401/shared-life-systems",
          "label": "Shared Life Systems"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/fellowship-leadership",
          "label": "Fellowship Leadership"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/integrated-scenario-performance",
          "label": "Integrated Scenario Performance"
        },
        {
          "objectiveId": "mens-relationship-skills:objectives/course/mrs-499/portfolio-self-audit",
          "label": "Portfolio Self Audit"
        }
      ]
    },
    {
      "sourceId": "performing-arts",
      "title": "Open Education Performing Arts",
      "sourceRepo": "open-education-performing-arts",
      "objectCount": 16,
      "courses": [
        {
          "id": "performing-arts:study-plans/courses/PERF-010-performance-onboarding-studio.md",
          "title": "PERF-010 - Performance Onboarding Studio",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-010-performance-onboarding-studio.md",
          "objectives": []
        },
        {
          "id": "performing-arts:study-plans/courses/PERF-101-voice-foundations.md",
          "title": "PERF-101 - Voice Foundations",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-101-voice-foundations.md",
          "objectives": []
        },
        {
          "id": "performing-arts:study-plans/courses/PERF-102-acting-foundations.md",
          "title": "PERF-102 - Acting Foundations",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-102-acting-foundations.md",
          "objectives": []
        },
        {
          "id": "performing-arts:study-plans/courses/PERF-201-voice-acting-and-character-performance.md",
          "title": "PERF-201 - Voice Acting and Character Performance",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-201-voice-acting-and-character-performance.md",
          "objectives": []
        },
        {
          "id": "performing-arts:study-plans/courses/PERF-301-camera-and-content-performance.md",
          "title": "PERF-301 - Camera and Content Performance",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-301-camera-and-content-performance.md",
          "objectives": []
        },
        {
          "id": "performing-arts:study-plans/courses/PERF-499-capstone-performance-portfolio.md",
          "title": "PERF-499 - Capstone Performance Portfolio",
          "sourceRepo": "open-education-performing-arts",
          "sourcePath": "study-plans\\courses\\PERF-499-capstone-performance-portfolio.md",
          "objectives": []
        }
      ],
      "objectives": [
        {
          "objectiveId": "performing-arts:objectives/course/perf-010/baseline-performance-map",
          "label": "Baseline Performance Map"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-010/deliberate-practice-plan",
          "label": "Deliberate Practice Plan"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-101/healthy-resonant-voice",
          "label": "Healthy Resonant Voice"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-101/listenable-pacing-and-articulation",
          "label": "Listenable Pacing And Articulation"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-102/objective-tactic-listening",
          "label": "Objective Tactic Listening"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-102/truthful-adjustment-under-direction",
          "label": "Truthful Adjustment Under Direction"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-201/character-contrast-and-vocal-choice",
          "label": "Character Contrast And Vocal Choice"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-201/microphone-performance-and-direction",
          "label": "Microphone Performance And Direction"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-301/camera-presence-and-eyeline",
          "label": "Camera Presence And Eyeline"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-301/teaching-and-creator-performance",
          "label": "Teaching And Creator Performance"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-499/multi-format-performance-reel",
          "label": "Multi Format Performance Reel"
        },
        {
          "objectiveId": "performing-arts:objectives/course/perf-499/review-driven-professional-growth",
          "label": "Review Driven Professional Growth"
        }
      ]
    },
    {
      "sourceId": "software-development",
      "title": "Open Education Software Development",
      "sourceRepo": "open-education-software-development",
      "objectCount": 12,
      "courses": [
        {
          "id": "software-development:study-plans/courses/SD-101-software-development-practice.md",
          "title": "SD-101 Software Development Practice",
          "sourceRepo": "open-education-software-development",
          "sourcePath": "study-plans\\courses\\SD-101-software-development-practice.md",
          "objectives": [
            {
              "objectiveId": "software-development:objectives/course/sd-101/problem-framing",
              "label": "Problem Framing"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/small-slices",
              "label": "Small Slices"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/readable-code",
              "label": "Readable Code"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/testable-functions",
              "label": "Testable Functions"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/debugging",
              "label": "Debugging"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/version-control",
              "label": "Version Control"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/error-handling",
              "label": "Error Handling"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/security-and-privacy",
              "label": "Security And Privacy"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/technical-communication",
              "label": "Technical Communication"
            },
            {
              "objectiveId": "software-development:objectives/course/sd-101/capstone-defense",
              "label": "Capstone Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "software-development:objectives/course/sd-101/capstone-defense",
          "label": "Capstone Defense"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/debugging",
          "label": "Debugging"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/error-handling",
          "label": "Error Handling"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/problem-framing",
          "label": "Problem Framing"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/readable-code",
          "label": "Readable Code"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/security-and-privacy",
          "label": "Security And Privacy"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/small-slices",
          "label": "Small Slices"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/technical-communication",
          "label": "Technical Communication"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/testable-functions",
          "label": "Testable Functions"
        },
        {
          "objectiveId": "software-development:objectives/course/sd-101/version-control",
          "label": "Version Control"
        },
        {
          "objectiveId": "software-development:objectives/debugging",
          "label": "Debugging"
        },
        {
          "objectiveId": "software-development:objectives/testable-functions",
          "label": "Testable Functions"
        },
        {
          "objectiveId": "software-development:objectives/version-control-basics",
          "label": "Version Control Basics"
        }
      ]
    },
    {
      "sourceId": "american-history",
      "title": "Open Education American History",
      "sourceRepo": "open-education-american-history",
      "objectCount": 8,
      "courses": [
        {
          "id": "american-history:study-plans/courses/AMH-REFERENCE-PROGRAM.md",
          "title": "AMH-REFERENCE-PROGRAM American History: Evidence, Argument, And Research",
          "sourceRepo": "open-education-american-history",
          "sourcePath": "study-plans\\courses\\AMH-REFERENCE-PROGRAM.md",
          "objectives": [
            {
              "objectiveId": "american-history:objectives/course/amh-reference/diagnostic-restoration",
              "label": "Diagnostic Restoration"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/evidence-before-conclusion",
              "label": "Evidence Before Conclusion"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/chronology-and-geography",
              "label": "Chronology And Geography"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/primary-source-analysis",
              "label": "Primary Source Analysis"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/historical-argument",
              "label": "Historical Argument"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/historiography",
              "label": "Historiography"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/public-history-and-teaching",
              "label": "Public History And Teaching"
            },
            {
              "objectiveId": "american-history:objectives/course/amh-reference/research-prospectus-defense",
              "label": "Research Prospectus Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "american-history:objectives/course/amh-reference/chronology-and-geography",
          "label": "Chronology And Geography"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/diagnostic-restoration",
          "label": "Diagnostic Restoration"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/evidence-before-conclusion",
          "label": "Evidence Before Conclusion"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/historical-argument",
          "label": "Historical Argument"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/historiography",
          "label": "Historiography"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/primary-source-analysis",
          "label": "Primary Source Analysis"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/public-history-and-teaching",
          "label": "Public History And Teaching"
        },
        {
          "objectiveId": "american-history:objectives/course/amh-reference/research-prospectus-defense",
          "label": "Research Prospectus Defense"
        }
      ]
    },
    {
      "sourceId": "leadership",
      "title": "Open Education Leadership",
      "sourceRepo": "open-education-leadership",
      "objectCount": 7,
      "courses": [
        {
          "id": "leadership:study-plans/courses/LEAD-101-leadership-practice-and-judgment.md",
          "title": "LEAD-101 Leadership Practice and Judgment",
          "sourceRepo": "open-education-leadership",
          "sourcePath": "study-plans\\courses\\LEAD-101-leadership-practice-and-judgment.md",
          "objectives": [
            {
              "objectiveId": "leadership:objectives/course/lead-101/leadership-as-responsibility",
              "label": "Leadership As Responsibility"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/listening-sensemaking",
              "label": "Listening Sensemaking"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/communication-intent",
              "label": "Communication Intent"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/decision-quality",
              "label": "Decision Quality"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/trust",
              "label": "Trust"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/conflict-repair",
              "label": "Conflict Repair"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/coaching-feedback",
              "label": "Coaching Feedback"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/team-systems",
              "label": "Team Systems"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/ethical-pressure",
              "label": "Ethical Pressure"
            },
            {
              "objectiveId": "leadership:objectives/course/lead-101/capstone-defense",
              "label": "Capstone Defense"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "leadership:objectives/course/lead-101/capstone-defense",
          "label": "Capstone Defense"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/change-leadership",
          "label": "Change Leadership"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/coaching-feedback",
          "label": "Coaching Feedback"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/communication-intent",
          "label": "Communication Intent"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/conflict-repair",
          "label": "Conflict Repair"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/crisis-aar",
          "label": "Crisis Aar"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/decision-quality",
          "label": "Decision Quality"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/ethical-pressure",
          "label": "Ethical Pressure"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/inclusion-fairness",
          "label": "Inclusion Fairness"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/leadership-as-responsibility",
          "label": "Leadership As Responsibility"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/listening-sensemaking",
          "label": "Listening Sensemaking"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/self-command",
          "label": "Self Command"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/team-systems",
          "label": "Team Systems"
        },
        {
          "objectiveId": "leadership:objectives/course/lead-101/trust",
          "label": "Trust"
        }
      ]
    },
    {
      "sourceId": "comedy",
      "title": "Open Education Comedy",
      "sourceRepo": "open-education-comedy",
      "objectCount": 7,
      "courses": [
        {
          "id": "comedy:study-plans/courses/COM-101-humor-writing-and-performance.md",
          "title": "COM-101 Humor Writing And Performance",
          "sourceRepo": "open-education-comedy",
          "sourcePath": "study-plans\\courses\\COM-101-humor-writing-and-performance.md",
          "objectives": [
            {
              "objectiveId": "comedy:objectives/course/com-101/humor-theories",
              "label": "Humor Theories"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/premise-notebook",
              "label": "Premise Notebook"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/incongruity-surprise",
              "label": "Incongruity Surprise"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/wordplay-language",
              "label": "Wordplay Language"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/observation-specificity",
              "label": "Observation Specificity"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/exaggeration-understatement",
              "label": "Exaggeration Understatement"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/irony-satire-parody",
              "label": "Irony Satire Parody"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/character-persona",
              "label": "Character Persona"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/story-comedy",
              "label": "Story Comedy"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/sketch-game",
              "label": "Sketch Game"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/improv-listening",
              "label": "Improv Listening"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/timing-delivery",
              "label": "Timing Delivery"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/audience-feedback",
              "label": "Audience Feedback"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/ethics-boundaries",
              "label": "Ethics Boundaries"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/revision-testing",
              "label": "Revision Testing"
            },
            {
              "objectiveId": "comedy:objectives/course/com-101/capstone-showcase",
              "label": "Capstone Showcase"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "comedy:objectives/course/com-101/audience-feedback",
          "label": "Audience Feedback"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/capstone-showcase",
          "label": "Capstone Showcase"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/character-persona",
          "label": "Character Persona"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/ethics-boundaries",
          "label": "Ethics Boundaries"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/exaggeration-understatement",
          "label": "Exaggeration Understatement"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/humor-theories",
          "label": "Humor Theories"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/improv-listening",
          "label": "Improv Listening"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/incongruity-surprise",
          "label": "Incongruity Surprise"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/irony-satire-parody",
          "label": "Irony Satire Parody"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/observation-specificity",
          "label": "Observation Specificity"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/premise-notebook",
          "label": "Premise Notebook"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/revision-testing",
          "label": "Revision Testing"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/sketch-game",
          "label": "Sketch Game"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/story-comedy",
          "label": "Story Comedy"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/timing-delivery",
          "label": "Timing Delivery"
        },
        {
          "objectiveId": "comedy:objectives/course/com-101/wordplay-language",
          "label": "Wordplay Language"
        }
      ]
    }
  ]
}
;

