// Generated by scripts/teaching/export-learner-ui-session.ps1.
// Do not edit by hand; update the source scripts or fixtures, then regenerate.
window.openEducationSessionOutput = 
{
  "schemaVersion": 1,
  "sessionAt": "2026-05-25T12:00:00Z",
  "learnerId": "gdev-101-live-smoke-learner",
  "action": {
    "learnerId": "gdev-101-live-smoke-learner",
    "actionType": "lesson",
    "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
    "reason": "no-mastery-evidence",
    "nextReviewAt": null,
    "evidence": "none"
  },
  "prompt": "Study the next source item and summarize what you learned.",
  "hintOptions": null,
  "learnerProfile": {
    "learnerId": "gdev-101-live-smoke-learner",
    "goals": [
      "game-development:objectives/course/gdev-101/design-vocabulary"
    ],
    "constraints": [
      "short-evening-sessions"
    ],
    "preferences": {
      "explanationStyle": "worked-example",
      "practiceMode": "scaffolded"
    },
    "accommodations": [
      "low-distraction-output"
    ],
    "priorExperience": [
      "played-games-but-new-to-design"
    ]
  },
  "mastery": [
    {
      "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
      "confidence": 0.0,
      "lastEvidenceAt": null,
      "evidenceCount": 0,
      "evidenceSources": []
    }
  ],
  "reviewQueue": [],
  "responseAccepted": false,
  "assessmentItemId": null,
  "feedback": "Read the source item and continue when ready.",
  "sourceProvenance": {
    "sourceId": "game-development",
    "sourceRepo": "open-education-game-development",
    "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
    "title": "GDEV-101 Game Design Foundations",
    "license": "CC-BY-4.0 for repo-authored metadata; linked third-party resources retain original licenses",
    "attribution": "Open Education Game Development"
  },
  "updatedStatePath": null
}
;
window.openEducationLecturePackage = 
{
  "schemaVersion": 1,
  "packageId": "lecture-video:gdev-101-design-vocabulary-short",
  "title": "Design Vocabulary: Verbs, Goals, and Feedback",
  "contentSource": {
    "sourceId": "game-development",
    "sourceRepo": "open-education-game-development",
    "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
    "title": "GDEV-101 Game Design Foundations"
  },
  "objectiveIds": [
    "game-development:objectives/course/gdev-101/design-vocabulary"
  ],
  "durationSeconds": 180,
  "lessonMode": "short-lecture",
  "renderStatus": "scripted-fixture",
  "generatedInstructor": {
    "personaId": "oes-default-generated-instructor-v1",
    "disclosure": "This lecture uses an original generated instructor and synthetic voice for an Open Education Suite lesson.",
    "voiceConsent": "synthetic-project-owned",
    "likenessConsent": "synthetic-project-owned",
    "realPersonClone": false,
    "tone": "clear-rigorous-supportive"
  },
  "sourceReview": [
    {
      "sourceType": "course-source",
      "title": "GDEV-101 Game Design Foundations",
      "sourceId": "game-development",
      "sourceRepo": "open-education-game-development",
      "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
      "usedFor": "grounding",
      "copyingAllowed": false,
      "notes": "Grounds the lesson in design vocabulary, verbs, goals, feedback, active prototyping, and playtest evidence."
    },
    {
      "sourceType": "teaching-pattern",
      "title": "Short studio lecture pattern",
      "usedFor": "structure-only",
      "copyingAllowed": false,
      "notes": "Uses a brief opening problem, worked example, active recall pause, misconception check, and practice handoff."
    }
  ],
  "citations": [
    {
      "citationId": "course-gdev-101",
      "sourceId": "game-development",
      "sourceRepo": "open-education-game-development",
      "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
      "claim": "The course covers design vocabulary, verbs, goals, feedback, playtesting, and prototypes."
    }
  ],
  "script": {
    "format": "markdown",
    "text": "# Design Vocabulary: Verbs, Goals, and Feedback\n\nToday we will use three design words precisely: verb, goal, and feedback. A verb is what the player can do. A goal is what the player is trying to accomplish. Feedback is how the game tells the player what changed and whether the action mattered. In GDEV-101, this vocabulary supports prototype critique and playtest evidence rather than personal preference alone. [course-gdev-101]\n\nConsider a simple rule-change prototype. If the player can only move, but there is no goal, the activity may be a toy instead of a game. If the goal exists but feedback is weak, the player cannot judge progress. Pause here: in a familiar game, name one verb, one goal, and one feedback signal.\n\nA common mistake is to describe theme instead of interaction. Saying a game is about space does not identify the verb. Saying the player wants to win does not identify the local goal. Strong critique names the action, the target, and the signal.\n\nAfter the video, revise one rule in a familiar game and write what changed in the verb, goal, or feedback loop. Bring that to the next practice checkpoint. [course-gdev-101]"
  },
  "storyboard": [
    {
      "sceneId": "open-problem",
      "startSecond": 0,
      "endSecond": 35,
      "visual": "Generated instructor beside a simple paper prototype with three labels: verb, goal, feedback.",
      "narrationCue": "Introduce the three vocabulary terms and connect them to critique.",
      "activeRecallPrompt": null,
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "worked-example",
      "startSecond": 35,
      "endSecond": 95,
      "visual": "Slide shows a tiny grid game: move token, reach star, tile lights up.",
      "narrationCue": "Work through one prototype example using verb, goal, and feedback.",
      "activeRecallPrompt": "Name the verb, goal, and feedback signal before the labels appear.",
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "misconception-check",
      "startSecond": 95,
      "endSecond": 135,
      "visual": "Split screen contrasts theme words with interaction words.",
      "narrationCue": "Separate theme from interaction and warn against vague critique.",
      "activeRecallPrompt": "Is 'space adventure' a verb, goal, feedback signal, or theme?",
      "citationIds": [
        "course-gdev-101"
      ]
    },
    {
      "sceneId": "practice-handoff",
      "startSecond": 135,
      "endSecond": 180,
      "visual": "Checklist for a rule-change prototype reflection.",
      "narrationCue": "Send the learner into the first GDEV-101 practice task.",
      "activeRecallPrompt": "Choose one familiar game and plan one rule change.",
      "citationIds": [
        "course-gdev-101"
      ]
    }
  ],
  "transcript": {
    "format": "plain-text",
    "language": "en",
    "text": "Today we will use three design words precisely: verb, goal, and feedback. A verb is what the player can do. A goal is what the player is trying to accomplish. Feedback is how the game tells the player what changed and whether the action mattered. Consider a simple rule-change prototype. If the player can only move, but there is no goal, the activity may be a toy instead of a game. If the goal exists but feedback is weak, the player cannot judge progress. Pause here: in a familiar game, name one verb, one goal, and one feedback signal. A common mistake is to describe theme instead of interaction. Saying a game is about space does not identify the verb. Saying the player wants to win does not identify the local goal. Strong critique names the action, the target, and the signal. After the video, revise one rule in a familiar game and write what changed in the verb, goal, or feedback loop."
  },
  "captions": {
    "format": "webvtt",
    "language": "en",
    "text": "WEBVTT\n\n00:00:00.000 --> 00:00:35.000\nToday we will use three design words precisely: verb, goal, and feedback.\n\n00:00:35.000 --> 00:01:35.000\nConsider a simple rule-change prototype. Pause here: in a familiar game, name one verb, one goal, and one feedback signal.\n\n00:01:35.000 --> 00:02:15.000\nA common mistake is to describe theme instead of interaction.\n\n00:02:15.000 --> 00:03:00.000\nAfter the video, revise one rule in a familiar game and write what changed."
  },
  "chapters": [
    {
      "title": "Vocabulary",
      "startSecond": 0
    },
    {
      "title": "Worked Example",
      "startSecond": 35
    },
    {
      "title": "Misconception Check",
      "startSecond": 95
    },
    {
      "title": "Practice Handoff",
      "startSecond": 135
    }
  ],
  "slides": [
    {
      "slideId": "slide-001",
      "title": "Verb, Goal, Feedback",
      "path": "slides\\001-verb-goal-feedback.md",
      "altText": "Three labels around a paper prototype: player verb, target goal, and feedback signal.",
      "attribution": "Original generated slide from the cited GDEV-101 course source."
    },
    {
      "slideId": "slide-002",
      "title": "Theme Is Not Interaction",
      "path": "slides\\002-theme-vs-interaction.md",
      "altText": "A comparison table separating vague theme words from concrete player actions and signals.",
      "attribution": "Original generated slide from the cited GDEV-101 course source."
    }
  ],
  "media": [
    {
      "assetId": "lecture-video-mp4",
      "type": "video/mp4",
      "path": "media\\gdev-101-design-vocabulary-short.mp4",
      "sha256": "pending-render",
      "status": "planned",
      "requiredForPublish": true
    },
    {
      "assetId": "lecture-audio-m4a",
      "type": "audio/mp4",
      "path": "media\\gdev-101-design-vocabulary-short.m4a",
      "sha256": "pending-render",
      "status": "planned",
      "requiredForPublish": true
    },
    {
      "assetId": "lecture-audio-wav-fixture",
      "type": "audio/wav",
      "path": "var\\lecture-media\\game-development\\lecture-video_gdev-101-design-vocabulary-short\\audio\\lecture-audio-wav.wav",
      "sha256": "5975a1f97d6315ba637dcfd46046c94c0e1be799db7e58317da4a18cc6239042",
      "status": "archived",
      "requiredForPublish": false
    }
  ],
  "licenseAudit": {
    "status": "pass",
    "externalHostDependency": false,
    "requiredInstructionArchive": "planned-local-render",
    "blockedMaterials": [],
    "notes": [
      "No copied third-party transcript, slides, voice, likeness, or hosted video is used.",
      "The lesson is an original generated artifact grounded in the cited course source."
    ]
  },
  "qaStatus": {
    "status": "pass",
    "checks": [
      {
        "checkId": "source-grounding",
        "status": "pass",
        "evidence": "Script and storyboard cite course-gdev-101."
      },
      {
        "checkId": "license-safety",
        "status": "pass",
        "evidence": "Generated instructor is synthetic and no external hosted media is required."
      },
      {
        "checkId": "accessibility",
        "status": "pass",
        "evidence": "Captions, transcript, chapters, and slide alt text are present."
      },
      {
        "checkId": "active-recall",
        "status": "pass",
        "evidence": "Storyboard includes recall prompts before answers are revealed."
      },
      {
        "checkId": "assessment-handoff",
        "status": "pass",
        "evidence": "Practice handoff asks for a rule-change prototype reflection."
      }
    ]
  },
  "operatorReview": {
    "workflowId": "lecture-operator-review-v1",
    "publishStatus": "not-ready",
    "stages": [
      {
        "stageId": "script",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:00:00Z",
        "evidence": [
          "Course citation markers are present.",
          "Narration is original and includes a misconception check."
        ],
        "notes": "Approved as a deterministic scripted fixture."
      },
      {
        "stageId": "visuals",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:01:00Z",
        "evidence": [
          "Slide plan uses original generated visuals.",
          "Slides include meaningful alt text and attribution."
        ],
        "notes": "Approved for storyboard and slide metadata."
      },
      {
        "stageId": "media",
        "status": "pending",
        "reviewer": null,
        "reviewedAt": null,
        "evidence": [],
        "notes": "Pending until rendered media has local archive paths and SHA-256 checksums."
      },
      {
        "stageId": "accessibility",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:02:00Z",
        "evidence": [
          "Transcript, WebVTT captions, chapters, and slide alt text are present."
        ],
        "notes": "Approved for the text and metadata fixture."
      },
      {
        "stageId": "license-persona",
        "status": "approved",
        "reviewer": "operator-fixture",
        "reviewedAt": "2026-05-25T12:03:00Z",
        "evidence": [
          "License audit passes.",
          "Generated instructor persona and disclosure match the approved policy."
        ],
        "notes": "Approved for synthetic instructor and source boundaries."
      },
      {
        "stageId": "final-package",
        "status": "pending",
        "reviewer": null,
        "reviewedAt": null,
        "evidence": [],
        "notes": "Pending until media is rendered, checksummed, and final package review is complete."
      }
    ],
    "finalApproval": {
      "status": "pending",
      "reviewer": null,
      "reviewedAt": null,
      "notes": "Final publish approval is blocked until all required stages are approved."
    }
  },
  "adaptiveHooks": {
    "availableModes": [
      "video",
      "transcript",
      "audio"
    ],
    "checkpointPolicy": "checkpoint-evidence-only",
    "checkpoints": [
      {
        "checkpointId": "identify-vgf",
        "timeSecond": 60,
        "prompt": "In a familiar game, identify one verb, one goal, and one feedback signal.",
        "evidenceType": "short-answer",
        "masteryImpact": "proposal-only"
      },
      {
        "checkpointId": "theme-vs-interaction",
        "timeSecond": 110,
        "prompt": "Is 'space adventure' a verb, goal, feedback signal, or theme?",
        "evidenceType": "multiple-choice",
        "masteryImpact": "proposal-only"
      }
    ],
    "followUpAction": {
      "type": "practice",
      "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
      "prompt": "Revise one rule in a familiar game and explain what changed in the verb, goal, or feedback loop."
    }
  }
}
;
window.openEducationContentCatalog = 
{
  "schemaVersion": 1,
  "generatedFrom": "scripts/ingestion/scan-content-sources.ps1",
  "sourceCount": 4,
  "sources": [
    {
      "sourceId": "cybersecurity",
      "title": "Open Education Cybersecurity",
      "sourceRepo": "open-education-cybersecurity",
      "objectCount": 6,
      "courses": [],
      "objectives": [
        {
          "objectiveId": "cybersecurity:objectives/incident-triage",
          "label": "Incident Triage"
        },
        {
          "objectiveId": "cybersecurity:objectives/network-fundamentals",
          "label": "Network Fundamentals"
        },
        {
          "objectiveId": "cybersecurity:objectives/threat-modeling-basics",
          "label": "Threat Modeling Basics"
        }
      ]
    },
    {
      "sourceId": "data-science",
      "title": "Open Education Data Science",
      "sourceRepo": "open-education-data-science",
      "objectCount": 6,
      "courses": [],
      "objectives": [
        {
          "objectiveId": "data-science:objectives/data-cleaning-basics",
          "label": "Data Cleaning Basics"
        },
        {
          "objectiveId": "data-science:objectives/regression-basics",
          "label": "Regression Basics"
        },
        {
          "objectiveId": "data-science:objectives/visualization-basics",
          "label": "Visualization Basics"
        }
      ]
    },
    {
      "sourceId": "game-development",
      "title": "Open Education Game Development",
      "sourceRepo": "open-education-game-development",
      "objectCount": 31,
      "courses": [
        {
          "id": "game-development:study-plans/courses/GDEV-010-onboarding-studio.md",
          "title": "GDEV-010 Onboarding Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-010-onboarding-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-010/toolchain-readiness",
              "label": "Toolchain Readiness"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-010/build-discipline",
              "label": "Build Discipline"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-101-game-design-foundations.md",
          "title": "GDEV-101 Game Design Foundations",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-101-game-design-foundations.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
              "label": "Design Vocabulary"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-101/prototype-iteration",
              "label": "Prototype Iteration"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-102-programming-for-games.md",
          "title": "GDEV-102 Programming for Games",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-102-programming-for-games.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-102/programming-fundamentals",
              "label": "Programming Fundamentals"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-102/code-architecture-basics",
              "label": "Code Architecture Basics"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-103-game-math-physics.md",
          "title": "GDEV-103 Game Math and Physics",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-103-game-math-physics.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-103/game-math",
              "label": "Game Math"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-103/game-physics",
              "label": "Game Physics"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-104-engine-tools-workflows.md",
          "title": "GDEV-104 Engine Tools and Workflows",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-104-engine-tools-workflows.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-104/engine-literacy",
              "label": "Engine Literacy"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-104/source-control-workflow",
              "label": "Source Control Workflow"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-201-gameplay-systems-architecture.md",
          "title": "GDEV-201 Gameplay Systems Architecture",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-201-gameplay-systems-architecture.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-201/gameplay-systems",
              "label": "Gameplay Systems"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-201/technical-writing",
              "label": "Technical Writing"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-202-level-design-ux-narrative.md",
          "title": "GDEV-202 Level Design, UX, and Narrative",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-202-level-design-ux-narrative.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-202/level-flow",
              "label": "Level Flow"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-202/ux-research",
              "label": "Ux Research"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-203-art-animation-audio-ui-pipeline.md",
          "title": "GDEV-203 Art, Animation, Audio, and UI Pipeline",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-203-art-animation-audio-ui-pipeline.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-203/content-pipeline",
              "label": "Content Pipeline"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-203/feedback-polish",
              "label": "Feedback Polish"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-204-ai-simulation-procedural-systems.md",
          "title": "GDEV-204 AI, Simulation, and Procedural Systems",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-204-ai-simulation-procedural-systems.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-204/game-ai",
              "label": "Game Ai"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-204/procedural-systems",
              "label": "Procedural Systems"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-301-production-qa-analytics-live-ops.md",
          "title": "GDEV-301 Production, QA, Analytics, and Live Operations",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-301-production-qa-analytics-live-ops.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-301/production-planning",
              "label": "Production Planning"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-301/qa-analytics-liveops",
              "label": "Qa Analytics Liveops"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-302-multiplayer-online-systems.md",
          "title": "GDEV-302 Multiplayer and Online Systems",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-302-multiplayer-online-systems.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-302/networking-literacy",
              "label": "Networking Literacy"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-302/networked-prototype",
              "label": "Networked Prototype"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-303-performance-platforms-accessibility-compliance.md",
          "title": "GDEV-303 Performance, Platforms, Accessibility, and Compliance",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-303-performance-platforms-accessibility-compliance.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-303/performance-profiling",
              "label": "Performance Profiling"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-303/accessibility-compliance",
              "label": "Accessibility Compliance"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-401-specialization-studio.md",
          "title": "GDEV-401 Specialization Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-401-specialization-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-401/specialization-depth",
              "label": "Specialization Depth"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-401/external-critique",
              "label": "External Critique"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-402-team-style-vertical-slice-studio.md",
          "title": "GDEV-402 Team-Style Vertical Slice Studio",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-402-team-style-vertical-slice-studio.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-402/vertical-slice-production",
              "label": "Vertical Slice Production"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-402/interdisciplinary-handoff",
              "label": "Interdisciplinary Handoff"
            }
          ]
        },
        {
          "id": "game-development:study-plans/courses/GDEV-499-capstone-launch.md",
          "title": "GDEV-499 Capstone Launch",
          "sourceRepo": "open-education-game-development",
          "sourcePath": "study-plans\\courses\\GDEV-499-capstone-launch.md",
          "objectives": [
            {
              "objectiveId": "game-development:objectives/course/gdev-499/capstone-launch",
              "label": "Capstone Launch"
            },
            {
              "objectiveId": "game-development:objectives/course/gdev-499/portfolio-case-study",
              "label": "Portfolio Case Study"
            }
          ]
        }
      ],
      "objectives": [
        {
          "objectiveId": "game-development:objectives/accessibility-aware-design",
          "label": "Accessibility Aware Design"
        },
        {
          "objectiveId": "game-development:objectives/art-pipeline-literacy",
          "label": "Art Pipeline Literacy"
        },
        {
          "objectiveId": "game-development:objectives/audio-feedback-literacy",
          "label": "Audio Feedback Literacy"
        },
        {
          "objectiveId": "game-development:objectives/blueprint-to-cpp",
          "label": "Blueprint To Cpp"
        },
        {
          "objectiveId": "game-development:objectives/capstone-launch",
          "label": "Capstone Launch"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-010/build-discipline",
          "label": "Build Discipline"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-010/toolchain-readiness",
          "label": "Toolchain Readiness"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-101/design-vocabulary",
          "label": "Design Vocabulary"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-101/prototype-iteration",
          "label": "Prototype Iteration"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-102/code-architecture-basics",
          "label": "Code Architecture Basics"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-102/programming-fundamentals",
          "label": "Programming Fundamentals"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-103/game-math",
          "label": "Game Math"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-103/game-physics",
          "label": "Game Physics"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-104/engine-literacy",
          "label": "Engine Literacy"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-104/source-control-workflow",
          "label": "Source Control Workflow"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-201/gameplay-systems",
          "label": "Gameplay Systems"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-201/technical-writing",
          "label": "Technical Writing"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-202/level-flow",
          "label": "Level Flow"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-202/ux-research",
          "label": "Ux Research"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-203/content-pipeline",
          "label": "Content Pipeline"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-203/feedback-polish",
          "label": "Feedback Polish"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-204/game-ai",
          "label": "Game Ai"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-204/procedural-systems",
          "label": "Procedural Systems"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-301/production-planning",
          "label": "Production Planning"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-301/qa-analytics-liveops",
          "label": "Qa Analytics Liveops"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-302/networked-prototype",
          "label": "Networked Prototype"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-302/networking-literacy",
          "label": "Networking Literacy"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-303/accessibility-compliance",
          "label": "Accessibility Compliance"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-303/performance-profiling",
          "label": "Performance Profiling"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-401/external-critique",
          "label": "External Critique"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-401/specialization-depth",
          "label": "Specialization Depth"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-402/interdisciplinary-handoff",
          "label": "Interdisciplinary Handoff"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-402/vertical-slice-production",
          "label": "Vertical Slice Production"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-499/capstone-launch",
          "label": "Capstone Launch"
        },
        {
          "objectiveId": "game-development:objectives/course/gdev-499/portfolio-case-study",
          "label": "Portfolio Case Study"
        },
        {
          "objectiveId": "game-development:objectives/design-core-loop",
          "label": "Design Core Loop"
        },
        {
          "objectiveId": "game-development:objectives/game-ai-simulation",
          "label": "Game Ai Simulation"
        },
        {
          "objectiveId": "game-development:objectives/game-math-and-physics",
          "label": "Game Math And Physics"
        },
        {
          "objectiveId": "game-development:objectives/gameplay-architecture",
          "label": "Gameplay Architecture"
        },
        {
          "objectiveId": "game-development:objectives/level-flow",
          "label": "Level Flow"
        },
        {
          "objectiveId": "game-development:objectives/performance-profiling",
          "label": "Performance Profiling"
        },
        {
          "objectiveId": "game-development:objectives/playtest-driven-iteration",
          "label": "Playtest Driven Iteration"
        },
        {
          "objectiveId": "game-development:objectives/portfolio-case-study",
          "label": "Portfolio Case Study"
        },
        {
          "objectiveId": "game-development:objectives/qa-release-readiness",
          "label": "Qa Release Readiness"
        },
        {
          "objectiveId": "game-development:objectives/scope-control",
          "label": "Scope Control"
        },
        {
          "objectiveId": "game-development:objectives/team-style-handoff",
          "label": "Team Style Handoff"
        },
        {
          "objectiveId": "game-development:objectives/tools-and-pipeline",
          "label": "Tools And Pipeline"
        },
        {
          "objectiveId": "game-development:objectives/ui-ux-game-feedback",
          "label": "Ui Ux Game Feedback"
        },
        {
          "objectiveId": "game-development:objectives/unreal-basics",
          "label": "Unreal Basics"
        },
        {
          "objectiveId": "game-development:objectives/vertical-slice-production",
          "label": "Vertical Slice Production"
        },
        {
          "objectiveId": "game-development:objectives/vr-comfort-basics",
          "label": "Vr Comfort Basics"
        }
      ]
    },
    {
      "sourceId": "software-development",
      "title": "Open Education Software Development",
      "sourceRepo": "open-education-software-development",
      "objectCount": 6,
      "courses": [],
      "objectives": [
        {
          "objectiveId": "software-development:objectives/debugging",
          "label": "Debugging"
        },
        {
          "objectiveId": "software-development:objectives/testable-functions",
          "label": "Testable Functions"
        },
        {
          "objectiveId": "software-development:objectives/version-control-basics",
          "label": "Version Control Basics"
        }
      ]
    }
  ]
}
;

